[package]
name = "ct-ui"
description = "ContextTrace local-first desktop application."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "ct_ui"
crate-type = ["lib", "cdylib", "staticlib"]

[[bin]]
name = "context-trace"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
ct-domain.workspace = true
ct-application.workspace = true
ct-runtime.workspace = true
serde.workspace = true
tauri = { version = "2.11.5", features = [] }

[lints]
workspace = true
