//! The reconstructed context: what the model was looking at, and where it came
//! from.
//!
//! [`ContextSnapshot`] is an aggregate. Its invariant -- that the parts sum to
//! the whole -- is enforced at construction, so no consumer has to trust that
//! whichever adapter produced it remembered to reconcile its numbers.

use super::event::CompactionFacts;
use super::identity::{ContextItemId, SessionId, TurnNumber};
use super::provenance::{Confidence, Provenance, SourceRef};
use super::session::AgentKind;
use super::tokens::TokenCount;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fmt;

/// What kind of thing a context item is. Drives the composition breakdown.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ContextCategory {
    /// The agent's own base/system prompt.
    SystemInstructions,
    /// Instructions injected by the harness beneath the system prompt.
    DeveloperInstructions,
    /// AGENTS.md, CLAUDE.md and friends.
    RepositoryInstructions,
    /// JSON schemas for the tools the model may call. Usually invisible in
    /// logs, and therefore usually part of the residual.
    ToolDefinitions,
    UserMessages,
    AssistantMessages,
    Reasoning,
    ToolCalls,
    ToolOutputs,
    /// File contents pulled in by reads or attachments.
    FileContents,
    /// Compaction summaries and other replacements for dropped history.
    Summaries,
    /// The prompt that triggered this specific turn.
    CurrentPrompt,
    /// Context we know is present because the totals demand it, but cannot
    /// attribute to anything visible in the log.
    Unattributed,
    Other,
}

impl ContextCategory {
    pub fn label(&self) -> &'static str {
        match self {
            ContextCategory::SystemInstructions => "System instructions",
            ContextCategory::DeveloperInstructions => "Developer instructions",
            ContextCategory::RepositoryInstructions => "Repository instructions",
            ContextCategory::ToolDefinitions => "Tool definitions",
            ContextCategory::UserMessages => "User messages",
            ContextCategory::AssistantMessages => "Assistant messages",
            ContextCategory::Reasoning => "Reasoning",
            ContextCategory::ToolCalls => "Tool calls",
            ContextCategory::ToolOutputs => "Tool outputs",
            ContextCategory::FileContents => "File contents",
            ContextCategory::Summaries => "Summaries",
            ContextCategory::CurrentPrompt => "Current prompt",
            ContextCategory::Unattributed => "Unattributed",
            ContextCategory::Other => "Other",
        }
    }
}

/// Where a context item originated -- the answer to "why is this in my prompt?"
///
/// This is the instruction-tracing feature expressed as a type. For Claude Code
/// most of these are [`Confidence::Observed`], because the harness labels its
/// own injections.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "origin", rename_all = "snake_case")]
pub enum ContextSource {
    /// The agent's built-in system prompt.
    AgentSystemPrompt,
    /// An instruction file discovered in the repository.
    InstructionFile { path: String },
    /// Configuration supplied by the project or user settings.
    ProjectConfig { path: Option<String> },
    /// Injected at runtime by the harness: a hook, a skill listing, MCP server
    /// instructions, a plan file, a queued command.
    HarnessInjection { mechanism: String },
    /// Typed by the human.
    UserPrompt,
    /// Produced by running a tool.
    ToolExecution { tool: String },
    /// Content of a file read into context.
    FileRead { path: String },
    /// A summary standing in for compacted history.
    CompactionSummary,
    /// Generated by the model.
    ModelOutput,
    /// We cannot say.
    Unknown,
}

impl fmt::Display for ContextSource {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ContextSource::AgentSystemPrompt => f.write_str("agent system prompt"),
            ContextSource::InstructionFile { path } => write!(f, "instruction file {path}"),
            ContextSource::ProjectConfig { path: Some(p) } => write!(f, "project config {p}"),
            ContextSource::ProjectConfig { path: None } => f.write_str("project config"),
            ContextSource::HarnessInjection { mechanism } => write!(f, "harness: {mechanism}"),
            ContextSource::UserPrompt => f.write_str("user prompt"),
            ContextSource::ToolExecution { tool } => write!(f, "tool: {tool}"),
            ContextSource::FileRead { path } => write!(f, "file: {path}"),
            ContextSource::CompactionSummary => f.write_str("compaction summary"),
            ContextSource::ModelOutput => f.write_str("model output"),
            ContextSource::Unknown => f.write_str("unknown"),
        }
    }
}

/// One addressable thing occupying space in the model's context.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ContextItem {
    /// Stable across turns, so an item can be tracked through its lifecycle.
    pub id: ContextItemId,
    pub category: ContextCategory,
    /// Human-facing name: a filename, a tool invocation, a message summary.
    pub label: String,
    pub source: ContextSource,
    pub tokens: TokenCount,
    /// Turn at which this item first entered the context.
    pub first_seen_turn: Option<TurnNumber>,
    pub provenance: Provenance,
    /// Short excerpt for display. Full content is re-read via `provenance.source`.
    pub preview: Option<String>,
}

impl ContextItem {
    /// Overall confidence in this item: no stronger than either our belief that
    /// it is present or our belief in how large it is.
    pub fn confidence(&self) -> Confidence {
        self.provenance.confidence.weakest(self.tokens.confidence())
    }
}

/// A category's share of the context.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CategoryBreakdown {
    pub category: ContextCategory,
    pub tokens: u32,
    pub share: f32,
    pub item_count: usize,
    /// Weakest confidence among the contributing items.
    pub confidence: Confidence,
}

/// A single large context consumer, for the "largest contributors" view.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Contributor {
    pub id: ContextItemId,
    pub label: String,
    pub category: ContextCategory,
    pub source: ContextSource,
    pub tokens: u32,
    pub share: f32,
    pub confidence: Confidence,
}

/// A compaction that happened during the session.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CompactionEvent {
    pub turn: Option<TurnNumber>,
    pub facts: CompactionFacts,
    pub source: SourceRef,
}

impl CompactionEvent {
    /// Tokens removed, when both sides were reported.
    pub fn reduction(&self) -> Option<u32> {
        let before = self.facts.tokens_before?;
        let after = self.facts.tokens_after?;
        Some(before.saturating_sub(after))
    }
}

/// **The aggregate.** ContextTrace's best reconstruction of what one model
/// request contained.
///
/// Construct via [`ContextSnapshot::assemble`], which enforces the invariant
/// that item tokens plus residual equal the reported total. That is what makes
/// the percentages in the composition view meaningful: they are shares of a
/// number the agent itself reported, not of a number we invented by adding up
/// our own guesses.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ContextSnapshot {
    session_id: SessionId,
    agent: AgentKind,
    turn: TurnNumber,
    model: Option<String>,
    items: Vec<ContextItem>,
    total: TokenCount,
    /// Context present but unattributable -- in practice the hidden system
    /// prompt and tool JSON schemas.
    ///
    /// Naming this rather than smearing it across the visible categories is the
    /// difference between an honest breakdown and a flattering one.
    residual: u32,
    context_window: Option<u32>,
    /// The most recent compaction at or before this turn.
    preceding_compaction: Option<CompactionEvent>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum SnapshotError {
    /// The parts do not sum to the whole.
    Unbalanced {
        items_total: u64,
        residual: u32,
        declared_total: u32,
    },
}

impl fmt::Display for SnapshotError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            SnapshotError::Unbalanced {
                items_total,
                residual,
                declared_total,
            } => write!(
                f,
                "context snapshot does not balance: items ({items_total}) + residual ({residual}) != total ({declared_total})"
            ),
        }
    }
}

impl std::error::Error for SnapshotError {}

impl ContextSnapshot {
    /// Build a snapshot, rejecting any breakdown that does not add up.
    ///
    /// Normally reached through
    /// [`TokenCalibrator`](crate::services::TokenCalibrator), which produces
    /// balanced input by construction. The check is kept here anyway: the
    /// aggregate defends its own invariant regardless of who calls it.
    #[allow(clippy::too_many_arguments)]
    pub fn assemble(
        session_id: SessionId,
        agent: AgentKind,
        turn: TurnNumber,
        model: Option<String>,
        items: Vec<ContextItem>,
        total: TokenCount,
        residual: u32,
        context_window: Option<u32>,
        preceding_compaction: Option<CompactionEvent>,
    ) -> Result<Self, SnapshotError> {
        let items_total: u64 = items.iter().map(|i| i.tokens.tokens() as u64).sum();
        let declared_total = total.tokens();
        if items_total + residual as u64 != declared_total as u64 {
            return Err(SnapshotError::Unbalanced {
                items_total,
                residual,
                declared_total,
            });
        }
        Ok(Self {
            session_id,
            agent,
            turn,
            model,
            items,
            total,
            residual,
            context_window,
            preceding_compaction,
        })
    }

    pub fn session_id(&self) -> &SessionId {
        &self.session_id
    }
    pub fn agent(&self) -> AgentKind {
        self.agent
    }
    pub fn turn(&self) -> TurnNumber {
        self.turn
    }
    pub fn model(&self) -> Option<&str> {
        self.model.as_deref()
    }
    pub fn items(&self) -> &[ContextItem] {
        &self.items
    }
    pub fn total(&self) -> TokenCount {
        self.total
    }
    pub fn residual(&self) -> u32 {
        self.residual
    }
    pub fn context_window(&self) -> Option<u32> {
        self.context_window
    }
    pub fn preceding_compaction(&self) -> Option<&CompactionEvent> {
        self.preceding_compaction.as_ref()
    }

    /// Fraction of the model's context window this turn consumed.
    pub fn utilisation(&self) -> Option<f32> {
        let window = self.context_window?;
        (window > 0).then(|| self.total.tokens() as f32 / window as f32)
    }

    /// Composition by category, largest first, including the residual as an
    /// explicit [`ContextCategory::Unattributed`] row when non-zero.
    pub fn by_category(&self) -> Vec<CategoryBreakdown> {
        let total = self.total.tokens().max(1) as f32;
        let mut acc: BTreeMap<ContextCategory, (u32, usize, Confidence)> = BTreeMap::new();

        for item in &self.items {
            let entry = acc
                .entry(item.category)
                .or_insert((0, 0, Confidence::Observed));
            entry.0 = entry.0.saturating_add(item.tokens.tokens());
            entry.1 += 1;
            entry.2 = entry.2.weakest(item.confidence());
        }

        if self.residual > 0 {
            acc.insert(
                ContextCategory::Unattributed,
                (self.residual, 1, Confidence::Derived),
            );
        }

        let mut rows: Vec<CategoryBreakdown> = acc
            .into_iter()
            .map(|(category, (tokens, item_count, confidence))| CategoryBreakdown {
                category,
                tokens,
                share: tokens as f32 / total,
                item_count,
                confidence,
            })
            .collect();

        rows.sort_by(|a, b| b.tokens.cmp(&a.tokens).then(a.category.cmp(&b.category)));
        rows
    }

    /// The `limit` biggest individual context consumers.
    ///
    /// The workflow this exists for: a turn ballooned, and you want the 38k-token
    /// garbage tool result responsible, by name, in one glance.
    pub fn largest_contributors(&self, limit: usize) -> Vec<Contributor> {
        let total = self.total.tokens().max(1) as f32;
        let mut items: Vec<&ContextItem> = self.items.iter().collect();
        items.sort_by(|a, b| b.tokens.tokens().cmp(&a.tokens.tokens()));
        items
            .into_iter()
            .take(limit)
            .map(|i| Contributor {
                id: i.id.clone(),
                label: i.label.clone(),
                category: i.category,
                source: i.source.clone(),
                tokens: i.tokens.tokens(),
                share: i.tokens.tokens() as f32 / total,
                confidence: i.confidence(),
            })
            .collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::identity::FileId;

    fn item(label: &str, category: ContextCategory, tokens: u32) -> ContextItem {
        ContextItem {
            id: ContextItemId::new(label),
            category,
            label: label.into(),
            source: ContextSource::Unknown,
            tokens: TokenCount::calibrated(tokens, tokens),
            first_seen_turn: None,
            provenance: Provenance::observed(SourceRef::new(FileId(0), 0, 0, 1)),
            preview: None,
        }
    }

    fn assemble(items: Vec<ContextItem>, total: u32, residual: u32) -> Result<ContextSnapshot, SnapshotError> {
        ContextSnapshot::assemble(
            SessionId::new("s1").unwrap(),
            AgentKind::ClaudeCode,
            TurnNumber::FIRST,
            Some("claude-opus-4-8".into()),
            items,
            TokenCount::observed(total),
            residual,
            Some(200_000),
            None,
        )
    }

    #[test]
    fn unbalanced_snapshots_cannot_be_constructed() {
        let err = assemble(vec![item("a", ContextCategory::ToolOutputs, 100)], 500, 0)
            .expect_err("must reject a breakdown that does not add up");
        assert!(matches!(err, SnapshotError::Unbalanced { .. }));
    }

    #[test]
    fn balanced_snapshot_with_residual_is_accepted() {
        let snap = assemble(vec![item("a", ContextCategory::ToolOutputs, 400)], 500, 100).unwrap();
        assert_eq!(snap.total().tokens(), 500);
        assert_eq!(snap.residual(), 100);
    }

    #[test]
    fn residual_appears_as_an_explicit_category_row() {
        let snap = assemble(
            vec![
                item("big", ContextCategory::ToolOutputs, 600),
                item("small", ContextCategory::UserMessages, 200),
            ],
            1000,
            200,
        )
        .unwrap();

        let rows = snap.by_category();
        assert_eq!(rows[0].category, ContextCategory::ToolOutputs);
        assert_eq!(rows[0].tokens, 600);
        assert!((rows[0].share - 0.6).abs() < f32::EPSILON);

        let unattributed = rows
            .iter()
            .find(|r| r.category == ContextCategory::Unattributed)
            .expect("residual must be shown, never hidden");
        assert_eq!(unattributed.tokens, 200);

        // Shares are shares of the observed total, so they sum to 1.
        let sum: f32 = rows.iter().map(|r| r.share).sum();
        assert!((sum - 1.0).abs() < 1e-5, "category shares must sum to 1, got {sum}");
    }

    #[test]
    fn largest_contributors_ranks_by_size() {
        let snap = assemble(
            vec![
                item("npm test output", ContextCategory::ToolOutputs, 520),
                item("schema.ts", ContextCategory::FileContents, 300),
                item("prompt", ContextCategory::CurrentPrompt, 180),
            ],
            1000,
            0,
        )
        .unwrap();

        let top = snap.largest_contributors(2);
        assert_eq!(top.len(), 2);
        assert_eq!(top[0].label, "npm test output");
        assert_eq!(top[1].label, "schema.ts");
        assert!((top[0].share - 0.52).abs() < 1e-6);
    }

    #[test]
    fn utilisation_uses_the_observed_total() {
        let snap = assemble(vec![item("a", ContextCategory::ToolOutputs, 100_000)], 100_000, 0).unwrap();
        assert_eq!(snap.utilisation(), Some(0.5));
    }
}
